name: first workflow
on:
    push:
        branches: [ master ]
    Pull_trigger:
        branches: [ master ]
jobs:
  Job-One:
    name: First job
    runs-on: ubuntu-latest
    steps:
    - name: Step One
      uses: actions/checkout@v2
    - name: Step Two
      run: date "+%Y/%m/%d %H:%M:%S"

  Job-Two:
    name: Second job
    runs-on: windows-latest
    steps:
    - name: Step One
      uses: actions/checkout@v2
    - name: Step Two
      run: "echo %date:~-4%/%date:~3,2%/%date:~0,2% %time:~0,2%:%time:~3,2%:%time:~6,2%"

  Job-three:
    name: third job
    runs-on: MacOS-latest
    steps:
    - name: Step One
      uses: actions/checkout@v2
    - name: Step Two
      run: date "+%Y/%m/%d %H:%M:%S"

  Job-four:
    needs: [Job-One, Job-Two, Job-three]
    name: fourth job
    runs-on: ubuntu-latest
    steps:
    - name: Step One
      uses: actions/checkout@v2
    - name: Step Two
      run: "echo Thank you for using this workflow"
